[project]
name = "ae4423-examples"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "gurobipy>=12.0.3",
    "matplotlib>=3.10.7",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
